jwt:
  secret: y4G2Q0TmqLmto3dBLnPoU3nr8ep61Goo75VuX89EwIit0hH5kZy4G2Q0TmqLmto3dBLnPoU3nr8ep61Goo75VuX89EwIit0hH5kZ

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

balance-increase-job: "0 * * * * *"